version: "2.4"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 6432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      # - --indexer=http://subquery-node:3000
      - --subscription

  subquery-node-project-avax-testnet:
    image: onfinality/subql-node-ethereum:latest
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: "5432"
    volumes:
      - ./:/app
    command:
      - -f=app/project-avax-testnet.yaml
      - --multi-chain
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://subquery-node-project-avax-testnet:3000/ready
      interval: 3s
      timeout: 5s
      retries: 10
